name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get public IP
        id: ip
        run: echo "ip=$(curl -s https://api.ipify.org)" >> $GITHUB_OUTPUT

      - name: Whitelist IP on Hetzner Firewall
        uses: adnanjaw/ip-whitelist-on-hetznerfw@v2.2
        with:
          hetzner_api_key: ${{ secrets.HETZNER_APIKEY }}
          ip_address: ${{ steps.ip.outputs.ip }}
          firewall_name: fw-fearfm-app-001
          direction: in
          protocol: tcp
          port: 22
          cleanup: true

      - name: Run remote SSH command
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: 116.203.246.165
          username: fearfm
          key: ${{ secrets.SSH_PRIVATE_FEARFM_APP_001 }}
          port: 22
          script: |
            cd /var/fearfm/website
            task update
